from fastapi import FastAPI, UploadFile, File, HTTPException
from app.api.v1.endpoints import extraction
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
import io
from openpyxl import Workbook
#excel to pdf
import os
import subprocess
import tempfile

app = FastAPI()

origins = [
    "http://localhost",
    "http://localhost:4100",
    "https://fp2p-server-hqdfdjerfyfdakbz.eastus-01.azurewebsites.net",
    "https://fp2p-frontend-cwfqadh9egh6fwgd.eastus-01.azurewebsites.net",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(extraction.router, prefix="/api/v1", tags=["Extraction"])

@app.get("/")  # ping básico
def root():
    return {"status": "ok", "service": "fastapi-excel"}

@app.get("/health")  # para health check del App Service
def health():
    return JSONResponse({"status": "healthy"}, status_code=200)

@app.get("/generate-excel")
def generate_excel():
    wb = Workbook()
    ws = wb.active
    ws["A1"] = "Hello"
    ws["B1"] = "World"

    stream = io.BytesIO()
    wb.save(stream)
    stream.seek(0)

    return StreamingResponse(
        stream,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=generated.xlsx"},
    )

@app.post("/convert-to-pdf")
async def convert_to_pdf(file: UploadFile = File(...)):
    # Validar que se envió un archivo
    if not file:
        raise HTTPException(status_code=400, detail="No file uploaded")

    # Usamos carpeta temporal
    with tempfile.TemporaryDirectory() as tmpdir:
        input_path = os.path.join(tmpdir, file.filename)

        # Guardar el Excel en disco
        with open(input_path, "wb") as f:
            contents = await file.read()
            f.write(contents)

        try:
            # Ejecutar LibreOffice para convertir a PDF
            subprocess.run(
                [
                    "libreoffice",
                    "--headless",
                    "--invisible",
                    "--norestore",
                    "--convert-to",
                    "pdf:calc_pdf_Export:PageOrientation=landscape,FitToPage=true,Scale=100",
                    "--outdir",
                    tmpdir,
                    input_path,
                ],
                check=True,
            )

            pdf_filename = os.path.splitext(file.filename)[0] + ".pdf"
            pdf_path = os.path.join(tmpdir, pdf_filename)

            if not os.path.exists(pdf_path):
                raise HTTPException(
                    status_code=500, detail="PDF not generated by LibreOffice"
                )

            # Devolver el PDF como stream
            pdf_file = open(pdf_path, "rb")
            return StreamingResponse(
                pdf_file,
                media_type="application/pdf",
                headers={
                    "Content-Disposition": 'attachment; filename="converted.pdf"'
                },
            )

        except subprocess.CalledProcessError as e:
            print("Error converting file:", e)
            raise HTTPException(status_code=500, detail="Conversion failed")